name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby_version: ['3.1', '3.0', '2.7']
        rails_version: ['7.0', '6.1']

        include:
          - ruby_version: '3.0'
            rails_version: '6.0'

          - ruby_version: '2.7'
            rails_version: '6.0'

          - ruby_version: '2.6'
            rails_version: '6.1'
          - ruby_version: '2.6'
            rails_version: '6.0'
          - ruby_version: '2.6'
            rails_version: '5.2'
          - ruby_version: '2.6'
            rails_version: '5.1'
          - ruby_version: '2.6'
            rails_version: '5.0'
          - ruby_version: '2.6'
            rails_version: '4.2'
            bundler_version: '1'

          - ruby_version: '2.5'
            rails_version: '5.2'
          - ruby_version: '2.5'
            rails_version: '4.2'
            bundler_version: '1'

          - ruby_version: '2.4'
            rails_version: '5.2'
          - ruby_version: '2.4'
            rails_version: '4.2'
            bundler_version: '1'

          - ruby_version: '2.3'
            rails_version: '4.1'
            bundler_version: '1'

          - ruby_version: '2.2'
            rails_version: '5.2'
            bundler_version: '1'

    env:
      RAILS_VERSION: ${{ matrix.rails_version }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby_version }}"
          bundler: "${{ matrix.bundler_version }}"
          bundler-cache: true
        continue-on-error: ${{ (matrix.allow_failures == 'true') || (matrix.rails_version == 'edge') }}

      - run: sudo apt-get install graphviz

      - run: bundle exec rake
        continue-on-error: ${{ (matrix.allow_failures == 'true') || (matrix.rails_version == 'edge') }}
